### ISSUE TITLE
Сложная логика, будет очень сложно тестировать

### ISSUE THREAD

**Issue by coursar** [bertRC/house-service#5]
https://github.com/bertRC/house-service/blob/2bb2474a43cb88f2e7f83e617120b28386b12f01/src/main/java/ru/itpark/service/HouseService.java#L50-L53

Что будет, если добавится ещё пару вариантов поиска?

Метод станет неподдерживаемым.

**Comment by bertRC** [comment]
Сложная логика из-за того что много условий?
В таком случае как следует поступить? Сделать отдельные методы, т.е. отдельно для поиска по ценам, отдельно для поиска по району?

**Comment by coursar** [comment]
Разбить на простые условия и через `continue`
